---

- hosts: all
  become: true
  tasks:

  - name: Installation of Apache and PHP packages
    yum:
      name:
        -  httpd-devel.x86_64
        -  php.x86_64
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

...
